export const TableHeaders = [
  "ID",
  "User",
  "Email",
  "Status",
  "Transaction",
  "Action"
];

export const UsersData = [
  {
    id: 1,
    avatar: "",
    name: "Julius Burgus",
    email: "",
    status: "",
    transaction: "",
    action: "",
  },
  {
    id: 2,
    avatar: "",
    name: "Julius Burgus",
    email: "",
    status: "",
    transaction: "",
    action: "",
  },
  {
    id: 3,
    avatar: "",
    name: "Julius Burgus",
    email: "",
    status: "",
    transaction: "",
    action: "",
  },
  {
    id: 4,
    avatar: "",
    name: "Julius Burgus",
    email: "",
    status: "",
    transaction: "",
    action: "",
  },
  {
    id: 5,
    avatar: "",
    name: "Julius Burgus",
    email: "",
    status: "",
    transaction: "",
    action: "",
  },
  {
    id: 6,
    avatar: "",
    name: "Julius Burgus",
    email: "",
    status: "",
    transaction: "",
    action: "",
  },
  {
    id: 7,
    avatar: "",
    name: "Julius Burgus",
    email: "",
    status: "",
    transaction: "",
    action: "",
  },
  {
    id: 8,
    avatar: "",
    name: "Julius Burgus",
    email: "",
    status: "",
    transaction: "",
    action: "",
  },
  {
    id: 9,
    avatar: "",
    name: "Julius Burgus",
    email: "",
    status: "",
    transaction: "",
    action: "",
  },
];
